**Feature Selection**

**Retrival the important features, selecting an important features is very important step before going to ml**
- Droping the constant features(Regression and classification)
- information gain (classification)
- p-value(Regression)
- VIF (Regression)
- Forward selection and backward selection(Regression and classification )
- correlation with target column(Regression and classification)

In [ ]:
**Feature selection methods**
1. variance threshold:
    - based on variance we can decide the data is constant or varying 
    - Data is not varying much means, data has unique values
    - for example we have seen in loan dataset, loan trem :360
    - python by  default will use variance=0 it will drop those feaatures which are having variance =0
    - variance threshold is hyper parameter , we can keep threshold as any value.
    - based on internal team discussion
    - we will drop those feature which are having <= threshold value
    
2. P-value:
    - h0: there is no relation x and y
    - H1: there is relation x and y
    - p<0.05
    - Reject the Null hypothesis : **which means do not include the variable**
    - p>0.05
    - Not Reject the Null Hypothesis: **Which means include the variables**
    
3 Mutual info classify:
     
        - KNN and entropy  
        - IT will give the relation between input and output will pick which are having more relation
        - input vs output
            - 1 Entropy
            - 2 KNN
            -3 R-square: explainability about y based on x
    
4 Forward selection and backward selection 
     
    **Forward selection method**
        
        - start with empty set of features
        - Iterate throght each features ansd select the one feaature that improves model performances
        - continue adding features one by one till we meet our creteria
        
     **Backward selection method**
    
        - start with full set of features
        - Itreate through each feature by removing  the feature which is having less impact on the model
        - continue the process , till your performance is stable
        
- Both forward and backward selection methods are complex in  nature
- More time taken , will avoid in general

5 **Variance Inflation factor**(VIF):
    - VIF will give the anaylsis of multicollinearity
    - VIF will find the R-square value of each input feature wrt to other input feature
    - will keep one feature as input and other feature are consider as output in Regression equation
    - this will hkeep on iterate through all feature 
    - Every feature behave as input as well as output
    - As we know every regression line give Rsquare value from that value will fine VIF
    - will drop the feature which are having VIF>5 or VIF>10 based on iternal team discussion
    

In [1]:
import pandas as pd
dict1={'A':[100,200,300,400],
      'B':[1,2,3,4],
      'C':[10,20,30,40],
      'D':[10,10,10,10]}

df=pd.DataFrame(dict1)
df

A  B   C   D
0  100  1  10  10
1  200  2  20  10
2  300  3  30  10
3  400  4  40  10

In [2]:
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0) #threshold means varaince value 
vt.fit(df) # we want to drop the feature based on threshold

VarianceThreshold(threshold=0)

In [3]:
dir(vt)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_support_mask',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sklearn_auto_wrap_output_keys',
 '_transform',
 '_validate_data',
 '_validate_params',
 'feature_names_in_',
 'fit',
 'fit_transform',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'get_support',
 'inve

In [4]:
vt.variances_
#300 is first column variance(true)
#1.25 is second variance (true)
# 30 is column variance (true)
# 0 is fourth column variance(false)

array([300.  ,   1.25,  30.  ,   0.  ])

In [5]:
vt.get_support()

array([ True,  True,  True, False])

In [6]:
vt.get_params()# hyper parameter
# that we are providing inside the function

{'threshold': 0}

In [7]:
vt.threshold

0

In [8]:
vt.get_feature_names_out()

array(['A', 'B', 'C'], dtype=object)

In [9]:
#Apply on wine dataset
# Read the data
# Keep the threshold
# get new data

In [10]:
df1=pd.read_csv('C:\\Users\\91901\\OneDrive\\naresh it\\DATA SCIENCE\\PYTHON SESSION\\Linear Regression methods\\winequality_red.csv')
df1

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               NaN               NaN          NaN             NaN        NaN   
1               7.4             0.700         0.00             1.9      0.076   
2               NaN               NaN          NaN             NaN        NaN   
3               7.8             0.880         0.00             2.6      0.098   
4               NaN               NaN          NaN             NaN        NaN   
...             ...               ...          ...             ...        ...   
3193            6.3             0.510         0.13             2.3      0.076   
3194            NaN               NaN          NaN             NaN        NaN   
3195            5.9             0.645         0.12             2.0      0.075   
3196            NaN               NaN          NaN             NaN        NaN   
3197            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                     NaN                   NaN      NaN   NaN        NaN   
1                    11.0                  34.0  0.99780  3.51       0.56   
2                     NaN                   NaN      NaN   NaN        NaN   
3                    25.0                  67.0  0.99680  3.20       0.68   
4                     NaN                   NaN      NaN   NaN        NaN   
...                   ...                   ...      ...   ...        ...   
3193                 29.0                  40.0  0.99574  3.42       0.75   
3194                  NaN                   NaN      NaN   NaN        NaN   
3195                 32.0                  44.0  0.99547  3.57       0.71   
3196                  NaN                   NaN      NaN   NaN        NaN   
3197                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         NaN      NaN  
1         9.4      5.0  
2         NaN      NaN  
3         9.8      5.0  
4         NaN      NaN  
...       ...      ...  
3193     11.0      6.0  
3194      NaN      NaN  
3195     10.2      5.0  
3196      NaN      NaN  
3197     11.0      6.0  

[3198 rows x 12 columns]

In [11]:
df1=df1.dropna()
df1.reset_index(inplace=True)
df1.head()

index  fixed acidity  volatile acidity  citric acid  residual sugar  \
0      1            7.4              0.70         0.00             1.9   
1      3            7.8              0.88         0.00             2.6   
2      5            7.8              0.76         0.04             2.3   
3      7           11.2              0.28         0.56             1.9   
4      9            7.4              0.70         0.00             1.9   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.076                 11.0                  34.0   0.9978  3.51   
1      0.098                 25.0                  67.0   0.9968  3.20   
2      0.092                 15.0                  54.0   0.9970  3.26   
3      0.075                 17.0                  60.0   0.9980  3.16   
4      0.076                 11.0                  34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4      5.0  
1       0.68      9.8      5.0  
2       0.65      9.8      5.0  
3       0.58      9.8      6.0  
4       0.56      9.4      5.0

In [12]:
x=df1.drop('quality',axis=1)
y=df1['quality']

In [13]:
df1.columns

Index(['index', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

In [14]:
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0) 
vt.fit(df1)# make sure before fitting the dataframe,don't include output column
vt.variances_
vt.get_support()
cols=vt.get_feature_names_out()
df1[cols]

index  fixed acidity  volatile acidity  citric acid  residual sugar  \
0         1            7.4             0.700         0.00             1.9   
1         3            7.8             0.880         0.00             2.6   
2         5            7.8             0.760         0.04             2.3   
3         7           11.2             0.280         0.56             1.9   
4         9            7.4             0.700         0.00             1.9   
...     ...            ...               ...          ...             ...   
1594   3189            6.2             0.600         0.08             2.0   
1595   3191            5.9             0.550         0.10             2.2   
1596   3193            6.3             0.510         0.13             2.3   
1597   3195            5.9             0.645         0.12             2.0   
1598   3197            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.076                 11.0                  34.0  0.99780  3.51   
1         0.098                 25.0                  67.0  0.99680  3.20   
2         0.092                 15.0                  54.0  0.99700  3.26   
3         0.075                 17.0                  60.0  0.99800  3.16   
4         0.076                 11.0                  34.0  0.99780  3.51   
...         ...                  ...                   ...      ...   ...   
1594      0.090                 32.0                  44.0  0.99490  3.45   
1595      0.062                 39.0                  51.0  0.99512  3.52   
1596      0.076                 29.0                  40.0  0.99574  3.42   
1597      0.075                 32.0                  44.0  0.99547  3.57   
1598      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.56      9.4      5.0  
1          0.68      9.8      5.0  
2          0.65      9.8      5.0  
3          0.58      9.8      6.0  
4          0.56      9.4      5.0  
...         ...      ...      ...  
1594       0.58     10.5      5.0  
1595       0.76     11.2      6.0  
1596       0.75     11.0      6.0  
1597       0.71     10.2      5.0  
1598       0.66     11.0      6.0  

[1599 rows x 13 columns]

$Method-2$
**Information Gain**

In [15]:
from sklearn.feature_selection import mutual_info_classif
mi=mutual_info_classif(x,y)
mi

array([0.14837677, 0.05471027, 0.12041504, 0.07093125, 0.01409585,
       0.02668246, 0.03359698, 0.05358911, 0.0942247 , 0.03490705,
       0.10996541, 0.17944012])

In [16]:
import numpy as np

In [17]:
np.sum(mi)

0.940935005048636

In [18]:
len(mi)

12

In [19]:
val=pd.Series(mi)
val

0     0.148377
1     0.054710
2     0.120415
3     0.070931
4     0.014096
5     0.026682
6     0.033597
7     0.053589
8     0.094225
9     0.034907
10    0.109965
11    0.179440
dtype: float64

In [20]:
d=pd.DataFrame(mi,
              columns=['Information Gain'],index=x.columns)
d.sort_values('Information Gain', ascending=False)
# we need to select manually
# how ever python will provide top 5 or top 10 or top k
# using selectKBest

Information Gain
alcohol                       0.179440
index                         0.148377
volatile acidity              0.120415
sulphates                     0.109965
density                       0.094225
citric acid                   0.070931
fixed acidity                 0.054710
total sulfur dioxide          0.053589
pH                            0.034907
free sulfur dioxide           0.033597
chlorides                     0.026682
residual sugar                0.014096

In [21]:
from sklearn.feature_selection import SelectKBest,mutual_info_classif
top_5=SelectKBest(mutual_info_classif,k=5)
val=top_5.fit(x,y)
val

SelectKBest(k=5,
            score_func=<function mutual_info_classif at 0x0000024EFDDC6700>)

In [22]:
dir(val)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_params',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_support_mask',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sklearn_auto_wrap_output_keys',
 '_transform',
 '_validate_data',
 '_validate_params',
 'feature_names_in_',
 'fit',
 'fit_transform',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'ge